language: php
php:
  - 7.3
  - 7.4
  
# We don't want to run linux commands as super user
sudo: false

# Tell Travis CI to monitor only 'master' branch
branches:
only: master

install: 
   composer install

script:
  - vendor/bin/phpunit
